QuizWebClient/Controllers/DefaultController.cs
using QuizWebClient.WebQuizMasterService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizWebClient.Controllers
{
    /// <summary>
    /// Home controller
    /// </summary>
    public class DefaultController : Controller
    {
        WebQuizMasterServiceClient quizService = new WebQuizMasterServiceClient();
  
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Index(string authorInitials)
        {
            int userID = quizService.GetUserIdByName(authorInitials);

            if (userID != 0)
            {
                // If author exists go to Participate Controller / Join with ID of author as query string
                return RedirectToAction("Join", "Participate", new { id = userID });
            }
            else
            {
                // No author found. Return index view with error message
                ViewBag.Error = "Der er ingen underviser kaldet "  + authorInitials;
                return View();
            }
        }
    }
}

QuizWebClient/Controllers/ParticipateController.cs
using QuizWebClient.WebQuizMasterService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace QuizWebClient.Controllers
{
    public class ParticipateController : Controller
    {
        WebQuizMasterServiceClient quizService = new WebQuizMasterServiceClient();

        // GET Quiz where open and author id equals (id)
        // Called by DefaultController with author id as query string (id)

        public ActionResult Join(int id)
        {
            var model = quizService.GetQuizByUserID(id);

            if(model == null)
            {
                // no author found. return index view with error message

                ViewBag.Error = "Denne underviser har ingen quizzer som er åben for deltagelse.";

                return View();
            }
            return View(model);
        }

        #region Contestant Login GET/POST

        /// <summary>
        /// GET ContestantLogin
        /// Called by Index button, quizId as query string /Participate/Join/(id) 
        /// </summary>
        public ActionResult ContestantLogin(int id)
        {
            return View();
        }

        /// <summary>
        /// POST ContestantLogin
        /// FORM POST quizId as query string (id) and contestant name from input field
        /// </summary>
        [HttpPost]
        public ActionResult ContestantLogin(int id, string name)
        {
            // creates and return new Contestant
            if (!string.IsNullOrWhiteSpace(name))
            {
                Contestant model = quizService.InsertContestant(name, id);

                // Done, redirect the newly created contestant to Quiz controller, Wait view
                return RedirectToAction("Wait", "Quiz", new { contestantId = model.Id, quizId = id });
            }

            // Error message
            ViewBag.Error = "Du skal indtaste navn";
            // Try again GET ContestantLogin
            return View();
        }
        #endregion
    }
}

QuizWebClient/Controllers/QuestionController.cs
using QuizWebClient.WebQuizMasterService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizWebClient.Controllers
{
    public class QuestionController : Controller
    {
        WebQuizMasterServiceClient quizService = new WebQuizMasterServiceClient();

        // GET: Question
        public ActionResult Index(Guid contestantId, int quizId, int questionId)
        {
            ///
            /// FYI quizId is now quiz instance id; don't change
            ///

            // Out comment next line to redirect view afC:\Users\Ole\Source\Repos\My First Project\QuizMaster\QuizAdmin\UserViews\ter X(29) seconds 
            Response.AddHeader("Refresh", "30;url=/Quiz/Index/" + contestantId + "/" + quizId);

            Question question = quizService.GetQuestionToAnswer(contestantId, quizId, questionId);
            if (question == null)
            {
                // Return to quiz, and list of questions...
                return RedirectToAction("Index", "Quiz", new { contestantId = contestantId, quizId = quizId });
            }

            return View(question);
        }

        public ActionResult Answer(Guid contestantId, int quizId, int questionId, int answerId)
        {
            ///
            /// FYI quizId is now quiz instance id; don't change
            ///

            // DO STUFF
            bool answer = quizService.AttemptAnswer(quizId, contestantId, questionId, answerId);

             TempData["output"] = answer;

            // Return to quiz, and list of questions...
            return RedirectToAction( "Index", "Quiz",new { contestantId = contestantId, quizId = quizId });

        }
    }
}

QuizWebClient/Controllers/QuizController.cs
using QuizWebClient.WebQuizMasterService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizWebClient.Controllers
{
    public class QuizController : Controller
    {
        WebQuizMasterServiceClient quizService = new WebQuizMasterServiceClient();

        // GET: Quiz
        // Custom RouteConfig App_Start
        // "Quiz/{contestantId}/{action}/{quizId}"

        // Quiz is started, Model = List<QuestionViewModel>
        public ActionResult Index(Guid contestantId, int quizId)
        {

            // get and return view with model...
            var model = quizService.GetQuestionView(contestantId, quizId);
            if (model == null)
            {
                return View("Ended");
            }
            else
            {
                return View(model);
            }
        }

        public ActionResult Ended()
        {
            return View();
        }
        #region waiting view

        // Starting point, loads partial view _IsRunning every 2 seconds
        public ActionResult Wait(Guid contestantId, int quizId)
        {
            return View();
        }

        // Called every 2 seconds by Wait view
        // Partial view in Wait. Returns a button or something when quiz is running
        public PartialViewResult IsRunning(Guid contestantId, int quizId)
        {
            bool running = quizService.GetQuizRunningByQuizId(quizId);

            return PartialView("_IsRunning", running);
        }

        #endregion
    }
}

QuizWebClient/Views/Default/Index.cshtml
@{
    ViewBag.Title = "Quiz søgning";
}


<div class="row">
    <div class="col-lg-12">
        <h2>Quiz søgning</h2>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        @if (ViewBag.Error != null)
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.Error
            </div>
        }

        @using (Html.BeginForm())
        {
            <div class="form-group">
                <label for="authorInitials">Undervisers initialer</label>
                <input class="form-control" id="authorInitials" type="text" name="authorInitials" />
            </div>
            <input type="submit" class="btn btn-default" value="Find quiz" />
        }
    </div>
</div>

QuizWebClient/Views/Participate/ContestantLogin.cshtml
@{
    ViewBag.Title = "Deltager Login";
}


<div class="row">
    <div class="col-lg-12">
        <h2>Deltager login</h2>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        @if (ViewBag.Error != null)
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.Error
            </div>
        }
        @using (Html.BeginForm())
        {
            <div class="form-group">
                <label for="Contestant">Dit navn</label>
                <input class="form-control" id="Contestant" type="text" name="name" />
            </div>
            <input type="submit" class="btn btn-default" value="Login" />
        }
    </div>
</div>

QuizWebClient/Views/Participate/Join.cshtml
@model QuizWebClient.WebQuizMasterService.QuizInstance
@{
    ViewBag.Title = "Deltag i quiz";
}

@if (@Model == null)
{
    <div class="row">
        <div class="col-lg-12">
            <h2>Ingen åben quiz fundet</h2>
            <p>Denne underviser har ingen åben quiz at deltage i.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            @Html.ActionLink("Tilbage", "Index", "Default", null, new { @class = "btn btn-default" })
        </div>
    </div>
}
else
{
<div class="row">
    <div class="col-lg-12">
        <h2>@Model.Quiz.Title</h2>
        <p>@Model.Quiz.Description</p>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        @Html.ActionLink("Deltag", "ContestantLogin", new { id = Model.Id }, new { @class = "btn btn-default" })
    </div>
</div>
}

QuizWebClient/Views/Question/Index.cshtml
@model Question
@using QuizWebClient.WebQuizMasterService
@{
    ViewBag.Title = @Model.Header;
    var _quizId = ViewContext.RouteData.Values["quizId"];
    var _contestantId = ViewContext.RouteData.Values["contestantId"];
}


<div class="row">
    <div class="col-lg-8">
        <h2>@Model.Header</h2>
    </div>

    <div class="col-lg-4 text-right">
        <!-- Creates a time icon with countdown --> 
        <h3><i class="glyphicon glyphicon-time"></i> <span id="Count">30</span></h3>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <h3>@Model.Text</h3>
    </div>
    <div class="col-lg-12 question-list">
        <div class="list-group">
            @foreach (var item in Model.Answers)
            {
                <a href="@Url.Action("answer", "Question", new { contestantId = _contestantId, quizId = _quizId, questionId = Model.Id, answerId = item.Id })" class="list-group-item">
                    @item.Text
                </a>
            }
        </div>
    </div>
</div>

<!-- Script for the time icon and counter --> 
@section scripts{
    <script type="text/javascript">

    window.onload = function () {
        (function () {
            var counter = 30;
            setInterval(function () {
                counter--;
                if (counter >= 0)
                {
                   span = document.getElementById("Count");
                    span.innerHTML = counter;
                }
            }, 1000);
        })();
    }
    </script>
}
  

QuizWebClient/Views/Quiz/Ended.cshtml
@{
    ViewBag.Title = "Ended";
}

<h2>Quizzen er afsluttet</h2>

QuizWebClient/Views/Quiz/Index.cshtml
@model IEnumerable<QuestionViewModel>
@using QuizWebClient.WebQuizMasterService
@{
    ViewBag.Title = "Quizzen";
    var _quizId = ViewContext.RouteData.Values["quizId"];
    var _contestantId = ViewContext.RouteData.Values["contestantId"];
}


<div class="row">
    <div class="col-lg-12">
        <h2>Quizzen</h2>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <h3>LISTE AF SPØRGSMÅL</h3>
    </div>
</div>

<div class="row">
    <!-- TempData creates an output variable that confirms if answer i correct or false  -->
    <div class="col-lg-12">
        @if (TempData["output"] != null)
        {
            if ((bool)TempData["output"])
            {
                <div class="alert alert-success">
                    Du svarede rigtigt
                </div>
            }
            else
            {
                <div class="alert alert-danger">
                    Du svarede forkert
                </div>
            }
        }
    </div>
    <div class="col-lg-12 question-list">
        @foreach (var item in Model)
        {
            <div class="col-lg-4 question-item">
                <!--if Question is clickable OPEN or PENDING. Add button with question ID and quiz + contestant-->
                @if (item.State == State.OPEN || item.State == State.PENDING)
                {
                    <a href="@Url.Action("Index", "Question", new { contestantId = _contestantId, quizId = _quizId, questionId = item.QuestionId })" class="btn btn-block @item.State">
                        @if (item.State == State.OPEN)
                        {
                            <i class="glyphicon glyphicon-question-sign pull-left highlight">
                            </i>
                        }
                        else
                        {
                            <i class="glyphicon glyphicon-dashboard pull-left">
                            </i>
                        }
                        @item.Header
                    </a>
                }
                else
                {
                    <div class="btn btn-block  disabled @item.State">
                        @if (item.State == State.CORRECT)
                        {
                            <i class="glyphicon glyphicon-ok-circle pull-left">
                            </i>
                        }

                        @if (item.State == State.WRONG)
                        {
                            <i class="glyphicon glyphicon-remove-circle pull-left">
                            </i>
                        }

                        @if (item.State == State.LOCKED)
                        {
                            <i class="glyphicon glyphicon-ban-circle pull-left">

                            </i>
                        }
                        @item.Header
                    </div>
                }
            </div>
        }
    </div>
</div>

QuizWebClient/Views/Quiz/Wait.cshtml
@{
    ViewBag.Title = "Vent";
    // variables from route, url. Used in script as @Url.Action parameters
    var _quizId = ViewContext.RouteData.Values["quizId"];
    var _contestantId = ViewContext.RouteData.Values["contestantId"];
}


<div class="row">
    <div class="col-lg-12">
        <h2>Vent</h2>
    </div>
</div>

<div class="row">
    <!--Partial view, requested by and replaced by script in bottom of page every 2 seconds-->
    <!--PartialViewResult IsRunning method in Quiz controller-->
    <div class="col-lg-12" id="IsRunning">
        @Html.Action("IsRunning", "Quiz")
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        // Replace content every 2 second inside <div id="IsRunning">X</div>
        // PartialViewResult IsRunning method in Quiz controller
        $(function () {
            setInterval(function () {
                $('#IsRunning').load("@Url.Action("IsRunning", "Quiz", new { quizId = _quizId, contestantId = _contestantId })");
            }, 2000); // every 2 sec
        });
    </script>
}

QuizWebClient/Views/Quiz/_IsRunning.cshtml
@model bool?



@if (Model.HasValue && Model.Value)
{
    <p>Quizzen er startet</p>
    <!--fancy button, linked to Index view inside Quiz Controller-->
    @Html.RouteLink("Begynd", "PartialRoute", null, new { @class = "btn btn-primary btn-success btn-lg" });
}
else
{
    <p>Gør dig klar, quizzen starter lige om lidt…</p>
}

QuizWebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("QuizMaster", "Index", "Default", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Quizmaster</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("Scripts", false)
</body>
</html>